sgpc_core_homepage:
    path:     /
    defaults: { _controller: SgpcCoreBundle:Project:index }
       
sgpc_project_add:
    path:   /project/add
    defaults: { _controller: SgpcCoreBundle:Project:add }
    
sgpc_project_create:
    path:   /project/create
    defaults: { _controller: SgpcCoreBundle:Project:create }
    methods: POST