sgpc_core_homepage:
    path:     /
    defaults: { _controller: SgpcCoreBundle:Project:index }
       
sgpc_project_add:
    path:   /project/add
    defaults: { _controller: SgpcCoreBundle:Project:add }
    
sgpc_project_create:
    path:   /project/create
    defaults: { _controller: SgpcCoreBundle:Project:create }
    methods: POST

sgpc_project_delete:
    path:   /project/{id}/delete
    defaults: { _controller: SgpcCoreBundle:Project:delete }
    methods: [POST, DELETE]
    
sgpc_project_view:
    path:   /project/{id}/view
    defaults: { _controller: SgpcCoreBundle:Project:view }




sgpc_listing:
    path:     /listing
    defaults: { _controller: "SgpcCoreBundle:Listing:index" }

sgpc_listing_view:
    path:     /listing/{id}/view
    defaults: { _controller: "SgpcCoreBundle:Listing:view" }

sgpc_listing_add:
    path:     /listing/add
    defaults: { _controller: "SgpcCoreBundle:Listing:add" }

sgpc_listing_create:
    path:     /listing/create/{id}
    defaults: { _controller: "SgpcCoreBundle:Listing:create" }
    methods:  POST
    
    
    
sgpc_task:
    path:     /task
    defaults: { _controller: "SgpcCoreBundle:Task:index" }

sgpc_task_view:
    path:     /task/{id}/view
    defaults: { _controller: "SgpcCoreBundle:Task:view" }

sgpc_task_add:
    path:     /task/add
    defaults: { _controller: "SgpcCoreBundle:Task:add" }

sgpc_task_create:
    path:     /task/create/{id}
    defaults: { _controller: "SgpcCoreBundle:Task:create" }
    methods:  POST