#PROYECTOS

sgpc_core_homepage:
    path:     /
    defaults: { _controller: SgpcCoreBundle:Project:index }
       
sgpc_project_add:
    path:   /project/add
    defaults: { _controller: SgpcCoreBundle:Project:add }
    
sgpc_project_create:
    path:   /project/create
    defaults: { _controller: SgpcCoreBundle:Project:create }
    methods: POST

sgpc_project_delete:
    path:   /project/{id}/delete
    defaults: { _controller: SgpcCoreBundle:Project:delete }
    methods: [POST, DELETE]
    
sgpc_project_kanban:
    path:   /project/{id}/kanban
    defaults: { _controller: SgpcCoreBundle:Project:kanban }
    
sgpc_project_scrum:
    path:   /project/{id}/scrum
    defaults: { _controller: SgpcCoreBundle:Project:scrum }

sgpc_project_addmember:
    path:     /project/{id}/addMember/
    defaults: { _controller: SgpcCoreBundle:Project:addmember }


#LISTADOS

sgpc_listing:
    path:     /listing
    defaults: { _controller: "SgpcCoreBundle:Listing:index" }

sgpc_listing_view:
    path:     /listing/{id}/view
    defaults: { _controller: "SgpcCoreBundle:Listing:view" }

sgpc_listing_add:
    path:     /listing/add
    defaults: { _controller: "SgpcCoreBundle:Listing:add" }

sgpc_listing_create:
    path:     /listing/create/{id}
    defaults: { _controller: "SgpcCoreBundle:Listing:create" }
    methods:  POST
    
    
#SPRINTS

sgpc_sprint_view:
    path:     /sprint/{id}/view
    defaults: { _controller: "SgpcCoreBundle:Sprint:view" }

sgpc_sprint_add:
    path:     /sprint/add
    defaults: { _controller: "SgpcCoreBundle:Sprint:add" }

sgpc_sprint_create:
    path:     /sprint/create/{id}
    defaults: { _controller: "SgpcCoreBundle:Sprint:create" }
    methods:  POST
    
sgpc_sprint_store:
    path:     /sprint/{id}/store/
    defaults: { _controller: SgpcCoreBundle:Sprint:store }
    
sgpc_sprint_report:
    path:     /sprint/{id}/report
    defaults: { _controller: "SgpcCoreBundle:Sprint:report" }
    
    
#TAREAS    
    
sgpc_task:
    path:     /task
    defaults: { _controller: "SgpcCoreBundle:Task:index" }

sgpc_task_view:
    path:     /task/{id}/view
    defaults: { _controller: "SgpcCoreBundle:Task:view" }

sgpc_task_add:
    path:     /task/add
    defaults: { _controller: "SgpcCoreBundle:Task:add" }

sgpc_task_create:
    path:     /task/create/{id}/{idproj}
    defaults: { _controller: "SgpcCoreBundle:Task:create" }
    methods:  POST
    
sgpc_task_addmember:
    path:     /task/{id}/addmember/
    defaults: { _controller: SgpcCoreBundle:Task:addmember }
    
sgpc_task_store:
    path:     /task/{id}/store/
    defaults: { _controller: SgpcCoreBundle:Task:store }
    
sgpc_task_edit:
    path:     /task/edit/{id}
    defaults: { _controller: SgpcCoreBundle:Task:edit }

sgpc_task_update:
    path:     /task/update/{id}
    defaults: { _controller: SgpcCoreBundle:Task:update }
    methods: [POST, PUT]
    
    
#COMENTARIOS

sgpc_comment_create:
    path:     /comment/create/{id}
    defaults: { _controller: "SgpcCoreBundle:Comment:create" }
    methods:  POST
