<?php

namespace Sgpc\CoreBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
      public function getCommentsForTask($taskId)
    {
        $qb = $this->createQueryBuilder('c')
                   ->select('c')
                   ->where('c.task = :task_id')
                   ->addOrderBy('c.createdAt')
                   ->setParameter('task_id', $taskId);

        return $qb->getQuery()
                  ->getResult();
    }
}
