<?php

namespace Sgpc\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ListingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListingRepository extends EntityRepository
{
    public function findListsByProject($id)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT l
            FROM SgpcCoreBundle:Listing l
            JOIN l.project p
            WHERE p.id = :projectId
            ORDER BY l.id ASC'
        )->setParameter('projectId', $id)->getResult();
    }
}
  
 