<?php

namespace Sgpc\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
      public function getTasksForList($listId) {
        $qb = $this->createQueryBuilder('t')
                ->select('t')
                ->where('t.listing = :list_id')
                ->addOrderBy('t.name')
                ->setParameter('list_id', $listId);

        return $qb->getQuery()
                        ->getResult();
    }

}
