<?php

namespace Sgpc\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
      public function getTasksForList($listId) {
        $qb = $this->createQueryBuilder('t')
                ->select('t')
                ->where('t.listing = :list_id')
                ->addOrderBy('t.name')
                ->setParameter('list_id', $listId);

        return $qb->getQuery()
                        ->getResult();
    }
    
      public function getActiveTasksForProject($projectId) {
        $qb = $this->createQueryBuilder('t')
                ->select('t')
                ->where('t.project = :project_id')
                ->andWhere('t.isActive = true')
                ->addOrderBy('t.name')
                ->setParameter('project_id', $projectId);

        return $qb->getQuery()
                        ->getResult();
    }
    
}
