<?php

namespace Sgpc\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function findTasksByList($id)
    {
        return $this->getEntityManager()->createQuery(
            'SELECT t
            FROM SgpcCoreBundle:Task t
            JOIN t.listing l
            WHERE l.id = :listId
            ORDER BY t.id ASC'
        )->setParameter('listId', $id)->getResult();
    }
}
