<?php

namespace Sgpc\CoreBundle\Repository;

/**
 * WorklogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorklogRepository extends \Doctrine\ORM\EntityRepository
{
}
