sgpc_user_user:
    resource: "@SgpcUserBundle/Resources/config/routes/user.yml"
    prefix: /user
    
sgpc_project_project:
    resource: "@SgpcUserBundle/Resources/config/routes/project.yml"
    prefix: /project