sgpc_user_homepage:
    path:     /user/index
    defaults: { _controller: SgpcUserBundle:User:index }
    
sgpc_user_add:
    path:     /user/add
    defaults: { _controller: SgpcUserBundle:User:add }

sgpc_user_create:
    path:     /user/create
    defaults: { _controller: SgpcUserBundle:User:create }
    methods: POST
    
sgpc_user_edit:
    path:     /user/edit/{id}
    defaults: { _controller: SgpcUserBundle:User:edit }
    
sgpc_user_view:
    path:     /user/view/{id}
    defaults: { _controller: SgpcUserBundle:User:view }
    
sgpc_user_delete:
    path:     /user/delete/{id}
    defaults: { _controller: SgpcUserBundle:User:delete }

sgpc_user_redirect_add:
    path:     /user/create
    defaults:
        _controller: SgpcUserBundle:User:add
        path: /user/add
        permanent: true